### ISSUE TITLE
Accept tab as whitespace

### ISSUE THREAD

**Issue by frno7** [zeldin/shForth#6]
The tab character isn’t treated as proper whitespace in for example [ttester.fs](http://www.forth200x.org/tests/ttester.fs).

**Comment by zeldin** [comment]
```
3.4.1.1 Delimiters

If the delimiter is the space character, hex 20 (BL), control characters may be treated as delimiters. The set of conditions, if any, under which a space delimiter matches control characters is implementation defined.
 ```

This implementation defines no such set of conditions, control characters are never treated as BL.  This is fully compliant with the standard.
